language: ruby
before_install:
  - gem update --system
  - gem install bundler
gemfile:
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
  - gemfiles/6.1.gemfile
  - gemfiles/7.0.gemfile
rvm:
  - 2.7.6
  - 3.0.4
  - 3.1.2
script:
  - bundle exec rspec
